[model]
name = "kotoba-whisper-v2.0-ggml"
#name = "kotoba-whisper-v2.0-faster"
#name = "kotoba-whisper-v2.0"
#name = "kotoba-whisper-v2.1"
#name = "kotoba-whisper-v2.2"

[general]
output_format = "srt"

[vad]
threshold = 0.30
min_speech_duration_ms = 100
min_silence_duration_ms = 300
speech_pad_ms = 50